theme: jekyll-theme-minimal
title: Surface Texture Modulation via Buckling in Porous Inclined Mechanical Metamaterials
description: This contains the data and code for the publication in Extreme Mechanics Letters.
google_analytics: [UA-50387353-17]