theme: jekyll-theme-minimal
title: Surface Texture Modulation via Buckling in Porous Mechanical Metamaterials
description: [This contains the data and code for the publication in Advanced Materials.]
google_analytics: [UA-50387353-17]